# Permalinks
permalink:           pretty

# Setup
title:               Onuralp Taner
tagline:             Cloud and Software Architect
url:                 https://onuralp.net
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Onuralp Taner
  url:               https://twitter.com/onuralp
  email:             onuralp@hotmail.com

# Custom vars
version:             1.1.0
google_analytics:    UA-99319481-1
twitter:             onuralp
github:              onuralp
linkedin:            onuralptaner

meta:
  robots:              index, follow
  keywords:            Onuralp Taner, Cloud Computing, DevOps, Contractor
  classification:      Personal
  expires:             never
  distribution:        Global
  rating:              General
  language:            English

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
