# Permalinks
permalink:           pretty

# Setup
title:               Onuralp Taner
tagline:             Cloud and Software Architect
url:                 https://onuralptaner.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Onuralp Taner
  url:               https://twitter.com/onuralptaner
  email:             onuralp@hotmail.com

# Custom vars
version:             1.1.0
google_analytics:    UA-99319481-1
twitter:             onuralptaner
github:              onuralp

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
