version: 2
jobs:
  build:
    docker:
      - image: circleci/builder-base
    workdir: /home/circleci/project

    steps:
      - type: checkout
      - setup_remote_docker

      - run:
          name: Build service
          command: |
            sh ./.build/build.sh           

      - run:
           name: Tests
           command: |
            bash ./.build/run.sh

      - deploy:
          name: Push image to ecr
          command: |
            set -x
            bash ./.build/push.sh

  deploy:
    working_directory: /
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          name: Deploy to GCE
          command: |
            echo $GCE_SERVICE | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json            
            gcloud container clusters get-credentials digidentity --zone europe-west4-c --project api-project-132697350705

            kubectl set image deployment/website website=website:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master